apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otvaraj
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: otvaraj
    newName: rg.fr-par.scw.cloud/djnd/otvaraj
    newTag: '6b0a0f71028c0649783eb322207c57f5cfed6d31'
