apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otvaraj
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: otvaraj
    newName: rg.fr-par.scw.cloud/djnd/otvaraj
    newTag: 'e7a7675e0b68c3e98bfbe608585f1bb8e6a5cc9a'
