apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otvaraj
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: otvaraj
    newName: rg.fr-par.scw.cloud/djnd/otvaraj
    newTag: '53134e950f9e0b0afb10c85f8b8890dd91abeb97'
